### ISSUE TITLE
Confusion regarding the "stride" parameter in glVertexAttribPointer

### ISSUE THREAD

**Issue by oveddan** [danielepanozzo/cg-old#16]
I'm confused why, when following the [OpenGl drawing tutorial](https://open.gl/drawing), the first call to `glVertexAttribPointer`, where there is just a single input to the vertex shader, has 0 as a value for `stride`:

``` C++
glVertexAttribPointer(posAttrib, 2, GL_FLOAT, GL_FALSE, 0, 0);
```

While in the example where they add a second input, the value for stride is the total size of the inputs for each run of the fragment shader:

``` C++
GLint posAttrib = glGetAttribLocation(shaderProgram, "position");
glEnableVertexAttribArray(posAttrib);
glVertexAttribPointer(posAttrib, 2, GL_FLOAT, GL_FALSE,
                       5*sizeof(float), 0);

GLint colAttrib = glGetAttribLocation(shaderProgram, "color");
glEnableVertexAttribArray(colAttrib);
glVertexAttribPointer(colAttrib, 3, GL_FLOAT, GL_FALSE,
                       5*sizeof(float), (void*)(2*sizeof(float)));
```

Why does this `stride` parameter need to be set in the second example and not the first?  What consequences will setting it incorrectly result in?

**Comment by danielepanozzo** [comment]
We are going to discuss this on Monday. You don't need to specify a stride if you are using a single attribute, since there is no gap between the data associated with the vertices. If you have multiple attributes, you need to use offset and stride to tell opengl how to access them. Take a look at the reference manual for more precise info: https://www.opengl.org/sdk/docs/man4/html/glVertexAttribPointer.xhtml

**Comment by oveddan** [comment]
Thank you - I was thinking of adding a second attribute for color, since the color needs to vary per triangle.
