### ISSUE TITLE
Multiple VBOs or single VBO?

### ISSUE THREAD

**Issue by oveddan** [danielepanozzo/cg-old#18]
Is it considered best practice to:

a) Have a separate VBO for each triangle.  When that triangle is modified, just update the VBO for that triangle.

b) Have a single VBO storing all of the triangle verteces and colors.  When a single triangle is modified (for example dragged a slight bit) update all of the triangles in the buffer.

**Comment by danielepanozzo** [comment]
It depends on the size of the objects that you are drawing. If each object is made of hundreds of triangles, then (a) (one VBO per object) is the best option. If the objects are small b is preferred since you have less API's overhead (and trasfering a few kb more it will not affect the timing at all).

For the assignment, you can do it in any way you like.
