### ISSUE TITLE
[Assignment 1] What is the coordinate of the left upper corner of the image?

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/cg-old#76]
Can we say that the image is the plane where the "camera" stays, which is x-y plane?
If so, what is the coordinate of the left upper corner in the image?
Is it (0, 0, 0) or (-1, 0, 0) or something else?

**Comment by danielepanozzo** [comment]
It does not matter what you pick as origin, as long as you are consistent in your implementation. In the provided code, the first pixel (called origin) is placed at the coordinates (-1,1,1) and the other pixels are distributed in such a way to cover a square in the z=1 plane, that goes from -1,1,1 to 1,-1,1. This would be way easier to explain on a whiteboard, I recommend that you reach out to Hanxiao and discuss it with him. Otherwise, send me an email and we can find a slot to chat on Friday when I will be back in NYC.
