### ISSUE TITLE
Task 1-5 Shadows

### ISSUE THREAD

**Issue by tomhsu1990** [danielepanozzo/cg-old#9]
Hi,
In tasks 1-1 to 1-4, if the intersection point is blocked by other objects from the light source, it is still visible from the light source. But for task 1-5, it is not visible and we need to create its shadow. Do I misunderstand the problems between 1-5 and previous ones? I am a little bit confused. Or we should create a floor to demonstrate the shadow for task 1-5.
By the way, for task 1-4 and 1-5, we only need to show perspective projection results, right?

**Comment by danielepanozzo** [comment]
In 1-5 you have to add "shadow rays" to your implementation, i.e. every time you will evaluate the lighting equation you will have to first check if the light is visible from that point. If you want, you can add a floor and have the objects in the scene cast shadows on the floor, but it is not necessary --- you can simply move the objects around so that the shadow casted by one object is visible on another one in the scene.

> By the way, for task 1-4 and 1-5, we only need to show perspective projection results, right?

Yes
