### ISSUE TITLE
[Assignment 2] task 1 - task 3: Do we need to consider preventing viewport distortion?

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/cg-old#97]
For task 1, task 2 and task 3, do we need to consider preventing viewport distortion?

Thank you

**Comment by danielepanozzo** [comment]
It is not required to maintain the aspect ratio if the viewport size changes (for example when the window is resized). While it is not required, it is a good idea to do it, since for doing it you need anyway a machinery similar to what you have to do for Task 4. 

Note that, however, all tasks should work even if you change the size, i.e. if you click in a point to create a triangle, the vertex should be inserted in the exact location of the cursor even after the window has been resized.

**Comment by LihengGong** [comment]
Thank you Prof.
